[build]
command = "npm run env:check:remote-db && npx prisma migrate deploy && npx prisma generate && npm run build -- --webpack"
publish = ".next"

[build.environment]
NODE_VERSION = "20"

[context.production]
command = "npm run env:check:remote-db && npx prisma migrate deploy && npx prisma generate && npm run build -- --webpack"
